name: Update Combined EPG

on:
  schedule:
    # سيتم التشغيل كل 12 ساعة (الساعة 00:00 و 12:00 بتوقيت UTC)
    - cron: '0 */12 * * *'
  workflow_dispatch: # يتيح لك تشغيل السكربت يدوياً من واجهة GitHub
  push:
    branches:
      - main # يعمل عند تحديث الكود في فرع main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run EPG Script
      run: python combined_epg_script.py # تأكد أن هذا هو نفس اسم ملف البايثون الخاص بك

    - name: Commit and push if changed
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add combined_epg_final.xml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update EPG Guide $(date)" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
